sh_binary(
    name = "helloWorld",
    srcs = ["helloWorld.sh"],
    data = ["//resources:json_resources"],
)

sh_test(
    name = "helloWorldTest",
    size = "small",
    srcs = ["helloWorld.sh"],
    data = ["//resources:json_resources"],
)