py_binary(
    name = "helloWorld",
    srcs = ["helloWorld.py"],
    data = ["//resources:json_resources"],
)

py_test(
    name = "helloWorldTest",
    srcs = ["helloWorldTest.py"],
    data = ["//resources:json_resources"],
)